Repository PCMDI/pcmdi_metrics, pull requests merged in 2023-04, with the labels that each got.

#918 Update setup.py
  pcmdi_metrics/version.py
  setup.py
Labels: build

#920 Mean clim patch
  pcmdi_metrics/graphics/parallel_coordinate_plot/parallel_coordinate_plot_lib.py
  pcmdi_metrics/graphics/share/read_json_mean_clim.py
  pcmdi_metrics/mean_climate/lib/create_mean_climate_parser.py
  pcmdi_metrics/mean_climate/lib/load_and_regrid.py
  pcmdi_metrics/mean_climate/mean_climate_driver.py
  pcmdi_metrics/mean_climate/param/pcmdi_MIP_EXP_pmp_parameterfile.py
  pcmdi_metrics/mean_climate/scripts/allvars_parallel_mod_clims.py
  pcmdi_metrics/mean_climate/scripts/get_all_MIP_mods_from_CLIMS.py
  pcmdi_metrics/mean_climate/scripts/mk_CRF_clims.py
  pcmdi_metrics/version.py
Labels: bug, enhancement

#913 868 msa precip distribution bimodality
  pcmdi_metrics/precip_distribution/lib/cluster3_pdf.amt_regrid.360x180_IMERG_ALL.nc
  pcmdi_metrics/precip_distribution/lib/cluster3_pdf.amt_regrid.360x180_IMERG_ALL_90S90N.nc
  pcmdi_metrics/precip_distribution/lib/lib_precip_distribution.py
  pcmdi_metrics/precip_distribution/param/precip_distribution_params_CFSR.py
  pcmdi_metrics/precip_distribution/param/precip_distribution_params_ERA-Interim.py
  pcmdi_metrics/precip_distribution/param/precip_distribution_params_ERA5.py
  pcmdi_metrics/precip_distribution/param/precip_distribution_params_GPCP.py
  pcmdi_metrics/precip_distribution/param/precip_distribution_params_IMERG.py
  pcmdi_metrics/precip_distribution/param/precip_distribution_params_JRA-55.py
  pcmdi_metrics/precip_distribution/param/precip_distribution_params_MERRA.py
  pcmdi_metrics/precip_distribution/param/precip_distribution_params_MERRA2.py
  pcmdi_metrics/precip_distribution/param/precip_distribution_params_PERSIANN.py
  pcmdi_metrics/precip_distribution/param/precip_distribution_params_TRMM.py
  pcmdi_metrics/precip_distribution/param/precip_distribution_params_cmip5.py
  pcmdi_metrics/precip_distribution/param/precip_distribution_params_cmip6.py
  pcmdi_metrics/precip_distribution/precip_distribution_driver.py
  pcmdi_metrics/precip_distribution/scripts_pcmdi/parallel_driver_cmip.py
  pcmdi_metrics/precip_distribution/scripts_pcmdi/run_model_parallel.bash
  pcmdi_metrics/precip_distribution/scripts_pcmdi/run_obs.bash
  pcmdi_metrics/precip_distribution/scripts_pcmdi/run_parallel.wait.bash
  setup.py
Labels: enhancement, New feature

#926 Open multiple files using xcdat
  .github/workflows/build_workflow.yml
  conda-env/dev.yml
  pcmdi_metrics/io/base.py
  pcmdi_metrics/mean_climate/lib/calculate_climatology.py
  pcmdi_metrics/mean_climate/lib/load_and_regrid.py
  setup.py
Labels: enhancement
