Repository PCMDI/pcmdi_metrics, pull requests merged in 2024-09, with the labels that each got.

#1117 Member update
  .all-contributorsrc
  README.md
Labels: doc

#1119 correlation output to 3 digits under decimal point
  pcmdi_metrics/mean_climate/lib/compute_metrics.py
Labels: enhancement, minor

#1121 correlation output to 3 digits under decimal point
  pcmdi_metrics/mean_climate/lib/compute_metrics.py
Labels: enhancement, minor

#1123 QC tools
  conda-env/dev.yml
  docs/conf.py
  docs/resources.rst
  docs/resources_legacy.rst
  docs/utils.rst
  pcmdi_metrics/utils/__init__.py
  pcmdi_metrics/utils/grid.py
  pcmdi_metrics/utils/land_sea_mask.py
  pcmdi_metrics/utils/qc.py
  tests/test_qc.py
Labels: enhancement, feature request

#1125 QC tool improve
  docs/utils.rst
  pcmdi_metrics/utils/__init__.py
  pcmdi_metrics/utils/qc.py
  tests/test_qc.py
Labels: enhancement

#1112 Code changes to implement PSA1 and PSA2 mode varibility analysis
  doc/jupyter/Demo/basic_mov_param.py.in
  doc/jupyter/Demo/basic_mov_param_sst.py.in
  pcmdi_metrics/io/regions.py
  pcmdi_metrics/variability_mode/lib/argparse_functions.py
  pcmdi_metrics/variability_mode/lib/eof_analysis.py
  pcmdi_metrics/variability_mode/lib/lib_variability_mode.py
  pcmdi_metrics/variability_mode/lib/plot_map.py
  pcmdi_metrics/variability_mode/variability_modes_driver.py
Labels: enhancement, build, graphic

#1132 Bug fix for the mean_climate and varibility_mode drivers
  pcmdi_metrics/mean_climate/mean_climate_driver.py
  pcmdi_metrics/variability_mode/lib/lib_variability_mode.py
Labels: bug, enhancement, minor

#1129 bug fix for wildcard use in multiple file open
  pcmdi_metrics/io/xcdat_openxml.py
Labels: bug

#1133 Bug fix in module mean_climate_driver.py for regional mean
  doc/jupyter/Demo/Demo_1a_compute_climatologies.ipynb
  doc/jupyter/Demo/Demo_1b_mean_climate.ipynb
  pcmdi_metrics/graphics/share/read_json_mean_clim.py
  pcmdi_metrics/io/regions.py
  pcmdi_metrics/mean_climate/mean_climate_driver.py
Labels: bug, enhancement, minor

#980 Regional capabilities for precip variability
  doc/jupyter/Demo/Demo_7_precip_variability.ipynb
  docs/metrics_precip-variability.rst
  pcmdi_metrics/io/__init__.py
  pcmdi_metrics/precip_variability/lib/__init__.py
  pcmdi_metrics/precip_variability/lib/argparse_functions.py
  pcmdi_metrics/precip_variability/lib/lib_variability_across_timescales.py
  pcmdi_metrics/precip_variability/variability_across_timescales_PS_driver.py
Labels: enhancement, New feature

#1143 clean up API doc page
  docs/api.rst
Labels: doc

#1144 Allow instant build and deploy of the website
  .github/workflows/build_workflow.yml
Labels: doc

#1145 add version info for API list in docs
  docs/api.rst
Labels: doc

#1148 improve docstrings for APIs
  pcmdi_metrics/io/region_from_file.py
  pcmdi_metrics/utils/tree_dict.py
Labels: doc, minor

#1149 Improve doc and enable more functions in API doc
  README.md
  docs/api.rst
  pcmdi_metrics/io/__init__.py
  pcmdi_metrics/io/xcdat_dataset_io.py
  pcmdi_metrics/io/xcdat_openxml.py
  pcmdi_metrics/utils/__init__.py
  pcmdi_metrics/utils/dates.py
  pcmdi_metrics/utils/qc.py
  pcmdi_metrics/utils/tree_dict.py
Labels: doc

#1150 Improve docstring
  pcmdi_metrics/io/xcdat_openxml.py
Labels: doc, minor

#1151 Update xcdat_openxml.py
  pcmdi_metrics/io/xcdat_openxml.py
Labels: minor
