Repository PCMDI/pcmdi_metrics, pull requests merged in 2024-03, with the labels that each got.

#1068 mean climate bug fix for E3SMv2.1 evaluation
  pcmdi_metrics/mean_climate/lib/compute_metrics.py
  pcmdi_metrics/mean_climate/lib/load_and_regrid.py
  pcmdi_metrics/mean_climate/mean_climate_driver.py
Labels: bug

#1070 Clean up logos
  share/pcmdi/171101_doutriaux1_UVCDATLogo_446x119px_72dpi.png
  share/pcmdi/CDATLogoText_1898x863px_300dpi.png
  share/pcmdi/CDATLogoText_200x91px_72dpi.png
  share/pcmdi/CDATLogo_140x49px_72dpi.png
  share/pcmdi/CDATLogo_1866x651px_300dpi.png
  share/pcmdi/CDATLogo_200x70px_72dpi.png
  share/pcmdi/PCMDILogo-old-oblong_377x300px_72dpi.png
  share/pcmdi/PCMDILogo-old_348x300px_72dpi.png
Labels: minor

#1069 Add figure preprocessing scripts to precip variability metrics
  pcmdi_metrics/precip_variability/README.md
  pcmdi_metrics/precip_variability/scripts_pcmdi/calc_ps_area_freq_mean_regional.py
  pcmdi_metrics/precip_variability/scripts_pcmdi/calc_ps_area_mean_regional.py
  pcmdi_metrics/precip_variability/scripts_pcmdi/calc_ps_freq_mean_regional.py
Labels: graphic
