Repository PCMDI/pcmdi_metrics, pull requests merged in 2024-10, with the labels that each got.

#1153 Bug/1152 pi control multifile lee1043
  pcmdi_metrics/variability_mode/lib/lib_variability_mode.py
  pcmdi_metrics/variability_mode/variability_modes_driver.py
Labels: bug

#1157 doc typo fix
  pcmdi_metrics/utils/grid.py
Labels: doc, minor

#1139 Propose a change for floating number format for mean climate metrics …
  doc/jupyter/Demo/Demo_1a_compute_climatologies.ipynb
  doc/jupyter/Demo/Demo_1b_mean_climate.ipynb
  pcmdi_metrics/mean_climate/lib/compute_metrics.py
Labels: enhancement, DecisionNeededNow, minor

#1156 Additional clean up
  pcmdi_metrics/variability_mode/lib/__init__.py
  pcmdi_metrics/variability_mode/lib/lib_variability_mode.py
  pcmdi_metrics/variability_mode/variability_modes_driver.py
Labels: minor, clean up

#1158 README update
  README.md
Labels: doc, clean up

#1160 Turn off github action for draft PRs
  .github/workflows/build_workflow.yml
Labels: build, workflow

#1162 On-the-fly mean clim plot generation
  conda-env/ci.yml
  conda-env/dev.yml
  doc/jupyter/Demo/Demo_1b_mean_climate.ipynb
  pcmdi_metrics/mean_climate/lib/__init__.py
  pcmdi_metrics/mean_climate/lib/calculate_climatology.py
  pcmdi_metrics/mean_climate/lib/colormap.py
  pcmdi_metrics/mean_climate/lib/compute_metrics.py
  pcmdi_metrics/mean_climate/lib/load_and_regrid.py
  pcmdi_metrics/mean_climate/lib/plot_clim_maps.py
  pcmdi_metrics/mean_climate/mean_climate_driver.py
  pcmdi_metrics/stats/compute_statistics_dataset.py
Labels: workflow, graphic

#1166 mean clim patch for on-the-fly figure generations
  pcmdi_metrics/mean_climate/lib/load_and_regrid.py
  pcmdi_metrics/mean_climate/lib/plot_clim_maps.py
  pcmdi_metrics/mean_climate/mean_climate_driver.py
Labels: bug, minor

#1167 Minor patch for mean clim on-the-fly plots
  pcmdi_metrics/mean_climate/lib/plot_clim_maps.py
  pcmdi_metrics/mean_climate/pcmdi_compute_climatologies.py
Labels: graphic
