Repository PCMDI/pcmdi_metrics, pull requests merged in 2024-05, with the labels that each got.

#1089 Update documentation for sea ice
  docs/metrics_sea_ice.rst
  pcmdi_metrics/sea_ice/README.md
Labels: doc

#1020 Update MoV code to use xCDAT
  .pre-commit-config.yaml
  conda-env/dev.yml
  doc/jupyter/Demo/Demo_4_modes_of_variability.ipynb
  pcmdi_metrics/graphics/portrait_plot/portrait_plot_lib.py
  pcmdi_metrics/io/__init__.py
  pcmdi_metrics/io/base.py
  pcmdi_metrics/io/regions.py
  pcmdi_metrics/io/string_constructor.py
  pcmdi_metrics/io/xcdat_dataset_io.py
  pcmdi_metrics/io/xcdat_openxml.py
  pcmdi_metrics/mean_climate/lib/__init__.py
  pcmdi_metrics/mean_climate/pcmdi_compute_climatologies.py
  pcmdi_metrics/monsoon_wang/monsoon_wang_driver.py
  pcmdi_metrics/precip_distribution/precip_distribution_driver.py
  pcmdi_metrics/stats/__init__.py
  pcmdi_metrics/stats/compute_statistics_dataArray.py
  pcmdi_metrics/stats/compute_statistics_dataset.py
  pcmdi_metrics/utils/__init__.py
  pcmdi_metrics/utils/create_target_grid.py
  pcmdi_metrics/utils/custom_season.py
  pcmdi_metrics/utils/grid.py
  pcmdi_metrics/utils/land_sea_mask.py
  pcmdi_metrics/utils/utils.py
  pcmdi_metrics/variability_mode/lib/__init__.py
  pcmdi_metrics/variability_mode/lib/adjust_timeseries.py
  pcmdi_metrics/variability_mode/lib/argparse_functions.py
  pcmdi_metrics/variability_mode/lib/calc_stat.py
  pcmdi_metrics/variability_mode/lib/eof_analysis.py
  pcmdi_metrics/variability_mode/lib/lib_variability_mode.py
  pcmdi_metrics/variability_mode/lib/north_test.py
  pcmdi_metrics/variability_mode/lib/plot_map.py
  pcmdi_metrics/variability_mode/param/myParam_pcmdi_NAM.py
  pcmdi_metrics/variability_mode/param/myParam_pcmdi_PDO.py
  pcmdi_metrics/variability_mode/param/myParam_pcmdi_SAM.py
  pcmdi_metrics/variability_mode/scripts_pcmdi/parallel_driver.py
  pcmdi_metrics/variability_mode/scripts_pcmdi/post_process_merge_jsons.py
  pcmdi_metrics/variability_mode/scripts_pcmdi/run_pmp_parallel.sh
  pcmdi_metrics/variability_mode/variability_modes_driver.py
Labels: enhancement, CRITICAL

#1092 New version (v3.4) release prepare
  README.md
  docs/index.rst
  setup.py
Labels: doc

#1093 Shapely patch for metrics with cdat
  pcmdi_metrics/enso/enso_driver.py
  pcmdi_metrics/monsoon_sperber/driver_monsoon_sperber.py
  pcmdi_metrics/precip_distribution/precip_distribution_driver.py
Labels: bug, build

#1094 Prepare v3.4.1 release
  README.md
  setup.py
Labels: build, doc
