Repository PCMDI/pcmdi_metrics, pull requests merged in 2024-12, with the labels that each got.

#1202 Monsoon Wang plots on the fly
  doc/jupyter/Demo/Demo_2a_monsoon_wang.ipynb
  pcmdi_metrics/monsoon_wang/lib/__init__.py
  pcmdi_metrics/monsoon_wang/lib/plot.py
  pcmdi_metrics/monsoon_wang/monsoon_wang_driver.py
Labels: enhancement, doc, graphic

#1205 Update README.md
  README.md
Labels: doc

#1206 v3.8 release preparation
  .zenodo.json
Labels: doc

#1207 Update citation info
  .zenodo.json
  CITATION.cff
Labels: doc

#1209 MoV code clean up
  README.md
  pcmdi_metrics/variability_mode/lib/calc_stat.py
  pcmdi_metrics/variability_mode/lib/eof_analysis.py
  pcmdi_metrics/variability_mode/lib/lib_variability_mode.py
  pcmdi_metrics/variability_mode/lib/north_test.py
  pcmdi_metrics/variability_mode/lib/plot_map.py
  pcmdi_metrics/variability_mode/variability_modes_driver.py
Labels: doc, minor, clean up

#1109 Add sftof file option to sea ice
  doc/jupyter/Demo/Demo_9_seaIceExtent_ivanova.ipynb
  docs/metrics_sea_ice.rst
  pcmdi_metrics/sea_ice/README.md
  pcmdi_metrics/sea_ice/lib/sea_ice_figures.py
  pcmdi_metrics/sea_ice/lib/sea_ice_lib.py
  pcmdi_metrics/sea_ice/lib/sea_ice_parser.py
  pcmdi_metrics/sea_ice/sea_ice_driver.py
Labels: enhancement

#1214 initial commit: change raise error to print warning
  pcmdi_metrics/variability_mode/variability_modes_driver.py
Labels: feature request, minor

#1218 Demo notebook clean up
  doc/jupyter/Demo/Demo_0_download_data.ipynb
  doc/jupyter/Demo/Demo_1a_compute_climatologies.ipynb
  doc/jupyter/Demo/Demo_1b_mean_climate.ipynb
  doc/jupyter/Demo/Demo_6_ENSO.ipynb
  doc/jupyter/Demo/Demo_7_precip_variability.ipynb
  doc/jupyter/Demo/Demo_8_extremes.ipynb
  doc/jupyter/Demo/Demo_9_seaIceExtent_ivanova.ipynb
  doc/jupyter/Demo/Demo_9b_seaIce_data_explore.ipynb
Labels: doc, clean up

#1215 New MoV plot: multi panel plot
  doc/jupyter/Demo/Demo_4_modes_of_variability.ipynb
  pcmdi_metrics/variability_mode/lib/__init__.py
  pcmdi_metrics/variability_mode/lib/eof_analysis.py
  pcmdi_metrics/variability_mode/lib/lib_variability_mode.py
  pcmdi_metrics/variability_mode/lib/plot_map.py
  pcmdi_metrics/variability_mode/variability_modes_driver.py
Labels: graphic

#1219 Allow more flexibility in ensemble member detection for MoV
  pcmdi_metrics/variability_mode/variability_modes_driver.py
Labels: enhancement

#1221 bug fix
  pcmdi_metrics/enso/enso_driver.py
Labels: bug
