Repository PCMDI/pcmdi_metrics, pull requests merged in 2024-04, with the labels that each got.

#1078 Update portrait_plot_lib.py
  pcmdi_metrics/graphics/portrait_plot/portrait_plot_example.ipynb
  pcmdi_metrics/graphics/portrait_plot/portrait_plot_lib.py
  pcmdi_metrics/graphics/portrait_plot/portrait_plot_mean_clim.ipynb
  pcmdi_metrics/graphics/portrait_plot/portrait_plot_mean_clim_multiple_CMIPs.ipynb
Labels: graphic

#1082 Add data files and model mask to sea ice metrics
  doc/jupyter/Demo/Demo_9_seaIceExtent_ivanova.ipynb
  pcmdi_metrics/sea_ice/sea_ice_driver.py
Labels: bug, enhancement

#1085 Custom season for MoV
  doc/jupyter/Demo/Demo_4_modes_of_variability.ipynb
  pcmdi_metrics/utils/__init__.py
  pcmdi_metrics/utils/custom_season.py
  pcmdi_metrics/variability_mode/lib/adjust_timeseries.py
Labels: enhancement, feature request

#1088 Parallel coordinate plot option added
  pcmdi_metrics/graphics/parallel_coordinate_plot/parallel_coordinate_plot_lib.py
Labels: enhancement, graphic

#1087 Add pole hole option to sea ice metrics
  pcmdi_metrics/sea_ice/lib/sea_ice_lib.py
  pcmdi_metrics/sea_ice/lib/sea_ice_parser.py
  pcmdi_metrics/sea_ice/sea_ice_driver.py
Labels: enhancement
