Repository PCMDI/pcmdi_metrics, pull requests merged in 2025-08, with the labels that each got.

#1307 mean clim json catalogue read in
  doc/jupyter/Demo/Demo_0_download_data.ipynb
  doc/jupyter/Demo/Demo_1a_compute_climatologies.ipynb
  doc/jupyter/Demo/Demo_1b_mean_climate.ipynb
  doc/jupyter/Demo/basic_param.py.in
  docs/supporting-data.rst
  pcmdi_metrics/mean_climate/mean_climate_driver.py
Labels: bug, enhancement, clean up

#1314 Mean clim demo patch
  doc/jupyter/Demo/Demo_1a_compute_climatologies.ipynb
  doc/jupyter/Demo/Demo_1b_mean_climate.ipynb
Labels: doc

#1308 NERSC mean climate run
  conda-env/ci.yml
  conda-env/dev.yml
  pcmdi_metrics/mean_climate/lib/load_and_regrid.py
  pcmdi_metrics/mean_climate/lib/plot_clim_maps.py
  pcmdi_metrics/mean_climate/mean_climate_driver.py
Labels: clean up

#1316 Allow users to specify a specific conda location
  pcmdi_metrics/io/base.py
Labels: enhancement
